version: '3.8'

services:
  gitlab-pages:
    build: .    # build custom image with Dockerfile
    container_name: ${CONTAINER_NAME}
    privileged: true
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      - "${SSH_PORT}:22"
    volumes:
      - "${ETC}:/etc/gitlab"
      - "${LOG}::/var/log/gitlab"
      - "${OPT}:/var/opt/gitlab"
      - "${PAGE_STORE}:/var/opt/gitlab/gitlab-rails/shared/pages"
    shm_size: ${SHM_SIZE}
    deploy:
      resources:
        limits:
          cpus: ${CPU}
          memory: ${MEM}